TOOLS-682 CoaL mac-vmware-setup Fusion 7 default code path. - Fail earlier if vms running. - Only restart Fusion services if Fusion running. - Restart Fusion services in Fusion 7.

diff --git a/tools/coal-mac-vmware-setup b/tools/coal-mac-vmware-setup
--- a/tools/coal-mac-vmware-setup
+++ b/tools/coal-mac-vmware-setup
@@ -9,8 +9,11 @@
 # Copyright (c) 2014, Joyent, Inc.
 #
 
-# coal-vmware-setup: sets up VMWare Fusion (on a Mac) so you can use
-# CoaL (Cloud on a Laptop) with it.
+# coal-vmware-setup: sets up VMWare Fusion networking on a Mac so
+#                    you can use CoaL (Cloud on a Laptop).
+#
+# Mac OS X 10.9.5 & VMware Fusion 7.0.0 are the most recent versions
+# developed for.
 
 if [[ -n "$TRACE" ]]; then
     export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
@@ -20,38 +23,42 @@ set -o errexit
 set -o pipefail
 
 
-
 if [[ "$(uname -s)" != "Darwin" ]]; then
-    echo "error: This script is written for a Mac" >&2
+    echo "error: This bash script is written for Mac OS X." >&2
     exit 1
 fi
 
 if [[ $UID -ne 0 ]]; then
     echo "error: This script must be run as root. Run again using:" >&2
-    echo "    sudo $0" >&2
+    echo "    sudo bash $0" >&2
     exit 1
 fi
 
-BIN_DIR=/Library/Application\ Support/VMware\ Fusion
-SETTINGS_DIR=/Library/Application\ Support/VMware\ Fusion
-NET_TMP=/tmp/coal.networking.$$
-LOCATIONS_TMP=/tmp/coal.locations.$$
 
-# Detect if Fusion 4 is installed
+if [[ -e "/Library/Application Support/VMware Fusion/boot.sh" ]]; then
+    echo "error: Fusion 3 is no longer supported." >&2
+    exit 1
+fi
+
+# Fusion 7. Fusion 6 is untested.
+BIN_DIR="/Applications/VMware Fusion.app/Contents/Library"
+SETTINGS_DIR="/Library/Preferences/VMware Fusion"
+# Detect if Fusion 4 or 5
 if [[ -e "/Applications/VMware Fusion.app/Contents/Library/services.sh" ]]; then
     BIN_DIR="/Applications/VMware Fusion.app/Contents/Library"
     SETTINGS_DIR="/Library/Preferences/VMware Fusion"
-    FUSION4=true
+    FUSION4_5=true
 fi
 
-# Detect if Fusion 7 is installed
-if [[ -e "/Applications/VMware Fusion.app/Contents/Library/vmrun" ]]; then
-    BIN_DIR="/Applications/VMware Fusion.app/Contents/Library"
-    SETTINGS_DIR="/Library/Preferences/VMware Fusion"
-    FUSION7=true
+
+VM_LIST=$("$BIN_DIR/vmrun" list)
+if [[ "$VM_LIST" != "Total running VMs: 0" ]]; then
+    printf "You have virtual machines running."
+    printf " Please shut them down and rerun $0."
+    exit 1
 fi
 
-## Networks ##
+
 # The admin "host-only" network - vmnet1 (only between the Mac and the headnode)
 ADMIN_NETWORK=10.99.99.0
 ADMIN_NETMASK=255.255.255.0
@@ -63,20 +70,16 @@ EXTERNAL_NETWORK=10.88.88.0
 EXTERNAL_NETMASK=255.255.255.0
 EXTERNAL_MAC_IP=10.88.88.1
 
+echo INPUT from $0 file:
 echo "Admin network:    network=\"${ADMIN_NETWORK}\", mac ip=\"${ADMIN_MAC_IP}\", netmask=\"${ADMIN_NETMASK}\""
 echo "External network: network=\"${EXTERNAL_NETWORK}\", mac ip=\"${EXTERNAL_MAC_IP}\", netmask=\"${EXTERNAL_NETMASK}\""
 
+
 cd "$SETTINGS_DIR"
 
-VM_LIST=$("$BIN_DIR/vmrun" list)
-if [[ "$VM_LIST" != "Total running VMs: 0" ]]; then
-    echo You have Virtual Machines running.  Please shut them down before continuing.
-    exit 1
-fi
 
-echo "Setup VMWare networking: admin network $ADMIN_NETWORK, external network $EXTERNAL_NETWORK"
+NET_TMP=/tmp/coal.networking.$$
 cat networking | (grep -ve 'VNET_[18]' || true) > $NET_TMP
-
 cat >> $NET_TMP <<__NETWORKING__
 answer VNET_1_DHCP no
 answer VNET_1_HOSTONLY_NETMASK $ADMIN_NETMASK
@@ -93,9 +96,20 @@ answer VNET_8_VIRTUAL_ADAPTER yes
 answer VNET_8_VIRTUAL_ADAPTER_ADDR $EXTERNAL_MAC_IP
 __NETWORKING__
 
+cp networking networking.pre_coal.$(date +%s)
+echo OLD networking settings backed up:
+echo     $SETTINGS_DIR/networking.pre_coal.$(date +%s)
+
+mv $NET_TMP networking
+echo UPDATED networking settings:
+echo $SETTINGS_DIR/networking
+
+
 if [[ -e locations ]]; then
+    # locations file doesn't exist in Fusion 7. Fusion 6 is untested.
+    LOCATIONS_TMP=/tmp/coal.locations.$$
     cat locations | (grep -ve 'VNET_[18]' || true) > $LOCATIONS_TMP
-cat >> $LOCATIONS_TMP <<__LOCATIONS__
+    cat >> $LOCATIONS_TMP <<__LOCATIONS__
 remove_answer VNET_1_HOSTONLY_HOSTADDR
 remove_answer VNET_1_HOSTONLY_NETMASK
 answer VNET_1_HOSTONLY_HOSTADDR $ADMIN_MAC_IP
@@ -112,38 +126,31 @@ remove_answer VNET_8_DHCP
 answer VNET_8_DHCP yes
 __LOCATIONS__
 
-echo Changing VMware locations settings...
+    cp locations locations.pre_coal.$(date +%s)
+    echo OLD locations settings backed up to the following file:
+    echo     $SETTINGS_DIR/locations.pre_coal.$(date +%s)
 
-cp locations locations.pre_coal
-
-echo Old locations settings backed up to the following files:
-echo     $SETTINGS_DIR/locations.pre_coal
-
-mv $LOCATIONS_TMP locations
+    mv $LOCATIONS_TMP locations
+    echo UPDATED locations settings:
+    echo $SETTINGS_DIR/locations
 fi
 
-echo Changing VMware networking settings...
 
-cp networking networking.pre_coal
-
-echo Old networking settings backed up to the following files:
-echo     $SETTINGS_DIR/networking.pre_coal
-
-mv $NET_TMP networking
-
-echo Restarting VMware services...
-if [[ -n "$FUSION4" ]]; then
-    "$BIN_DIR/services.sh" --stop
-    "$BIN_DIR/services.sh" --start
-elif [[ -n "$FUSION7" ]]; then
-    echo "Restart Fusion after this script finishes!"
-else
-    "$BIN_DIR/boot.sh" --restart
+if [[ $(ps axo command | grep "Fusion$") ]]; then
+    echo RESTARTING VMware services...
+    if [[ -n "$FUSION4_5" ]]; then
+        "$BIN_DIR/services.sh" --stop
+        "$BIN_DIR/services.sh" --start
+    else 
+        # Fusion 7. Fusion 6 is untested.
+        "$BIN_DIR/vmnet-cli" --configure
+        "$BIN_DIR/vmnet-cli" --stop
+        "$BIN_DIR/vmnet-cli" --start 
+    fi
 fi
 
 # If we're running before VMWare is run for the first time, the previous step
 # will have created a preference file as root, so fix it:
 chown -R $SUDO_UID:$SUDO_GID "/Users/$SUDO_USER/Library/Preferences/VMWare Fusion"
 
-echo Done!
-
+echo DONE. Fusion is ready for CoaL.
